### ISSUE TITLE
Error reporting broken

### ISSUE THREAD

**Issue by ddimtirov** [societe-generale/arch-unit-gradle-plugin#10]
At https://github.com/societe-generale/arch-unit-gradle-plugin/blob/master/src/main/java/com/societegenerale/commons/plugin/gradle/ArchUnitGradlePlugin.java#L30

The line

```
throw new GradleException("can't find the '"+taskToFind+"' task on which archUnitGradle task will depend - please check Gradle java plugin is applied");
```

Should be changed to:

```
throw new GradleException("can't find the '"+taskName+"' task on which archUnitGradle task will depend - please check Gradle java plugin is applied");
```

The current implementation always outputs:

> can't find the 'null' task on which archUnitGradle task will depend - please check Gradle java plugin is applied

Apologies for not submitting a patch, but it is a lot of red tape from my employer.

**Comment by vincent-fuchs** [comment]
Thanks a lot for reporting this ! I've done it and it will be available in next release (no planned date yet)
