### ISSUE TITLE
maven central does not have 1.1.0 version

### ISSUE THREAD

**Issue by paul58914080** [societe-generale/arch-unit-gradle-plugin#13]
I was trying to use `arch-unit-gradle-plugin` referring to the [releases](https://github.com/societe-generale/arch-unit-gradle-plugin/releases) the latest version and found **1.1.0** to be missing in [maven-central](https://mvnrepository.com/artifact/com.societegenerale.commons/arch-unit-gradle-plugin)

**Comment by vincent-fuchs** [comment]
but it is there on Gradle plugins portal : https://plugins.gradle.org/plugin/com.societegenerale.commons.arch-unit-gradle-plugin

If you follow instructions mentioned there, it should work

**Comment by paul58914080** [comment]
Thank you. It worked with the above.
