### ISSUE TITLE
Externalize the path of the classes in GradleScopePathProvider 

### ISSUE THREAD

**Issue by andres-sacco** [societe-generale/arch-unit-gradle-plugin#19]
The plugin works fine with Java projects but if you want to use it on Kotlin is not possible because in the class GradleScopePathProvider the path is hardcoded to "/classes/java/test".

**Comment by vincent-fuchs** [comment]
good idea. I've made some changes, I'll test them next week. 

Don't hesitatete to give it a try yourself and give me feedback : 
- build core from https://github.com/societe-generale/arch-unit-build-plugin-core/pull/51 (v 2.8.1-SNAPSHOT)
- then build the gradle  plugin from this PR, and see if it works as expected 

Thanks !!

**Comment by vincent-fuchs** [comment]
I've tried it quickly locally and it seems to be working.

can you please build it locally from https://github.com/societe-generale/arch-unit-gradle-plugin/tree/possibilityToOverrideMainAndTestPaths and try it ? new params have been added in the readme in the branch.
