### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by mosheeshel** [societe-generale/arch-unit-gradle-plugin#28]
Starting out with the plugin and ArchUnit in general, I performed the most basic setup as outlined in the readme - just wanted a default run, even with no rules.
```
buildscript {
    repositories {
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }

    }
    dependencies {
        classpath "com.societegenerale.commons:arch-unit-gradle-plugin:2.9.5"
    }
}


allprojects {
    apply plugin: "com.societegenerale.commons.arch-unit-gradle-plugin"
}
```
Got the error you see below. Any suggestions?

Running with:
Gradle 5.2.1
------------------------------------------------------------

Build time:   2019-02-08 19:00:10 UTC
Revision:     f02764e074c32ee8851a4e1877dd1fea8ffb7183

Kotlin DSL:   1.1.3
Kotlin:       1.3.20
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.4 (Oracle Corporation 11.0.4+11)
OS:           Linux 5.0.0-38-generic amd64

```
$ ./gradlew ArchUnitRulesTask 
OpenJDK 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0

FAILURE: Build failed with an exception.

* Where:
Build file '/home/moshee/dev/dashboards/build.gradle' line: 34

* What went wrong:
A problem occurred evaluating root project 'dashboards'.
> Failed to apply plugin [id 'com.societegenerale.commons.arch-unit-gradle-plugin']
   > Could not create task ':checkRules'.
      > Could not create task of type 'ArchUnitRulesTask'.
         > Could not generate a decorated class for class com.soc
```

**Comment by vincent-fuchs** [comment]
do you get the same if you run `gradlew checkRules`  ?

if you run the gradle build in debug mode, do you get a stacktrace that helps pinpointing the issue ?
