### ISSUE TITLE
Rule Violated - com.societegenerale.commons.plugin.rules.DontReturnNullCollectionTest

### ISSUE THREAD

**Issue by shantanuKumaSocgen** [societe-generale/arch-unit-gradle-plugin#35]
FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':domain:checkRules'.

> A failure occurred while executing com.societegenerale.commons.plugin.gradle.WorkerAction

   > ArchUnit Gradle plugin reported architecture failures listed below : 

     Rule Violated - com.societegenerale.commons.plugin.rules.DontReturnNullCollectionTest

     java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] - Rule 'methods that return collections and are not lambda should be annotated with @Nonnull, because we don't want callers to perform null check every time. Return an empty collection, not null. Please annotate the method with javax.annotation.Nonnull' was violated (2 times):

**Comment by paul58914080** [comment]
## Problem statement
We bumped our dependency versions to latest . For example : spring-boot which uses jakarta in place of javax. While we did that ,  the rule `com.societegenerale.commons.plugin.rules.DontReturnNullCollectionTest` is violated. Because the rule is checking for `javax` and not `jakarta`.
 
## To reproduce
Build a new spring boot to violate the  `DontReturnNullCollectionTest` and then annotate with `@Nonnull` imported from `jakarta`.

**Comment by shantanuKumaSocgen** [comment]
Closing this as I opened a new one at https://github.com/societe-generale/arch-unit-build-plugin-core/issues/74

**Comment by vincent-fuchs** [comment]
available in 4.0.0 , please give it a try !

**Comment by paul58914080** [comment]
Hello @vincent-fuchs , can you please release a 3x version by cherry picking the [commit](https://github.com/societe-generale/arch-unit-build-plugin-core/commit/e5f6097dd7d3d173dc891954e0f597d486ee8372) , as v4.0.0 requires jdk 21 and we are not yet at jdk 21.

```
Caused by: java.lang.UnsupportedClassVersionError: com/societegenerale/commons/plugin/maven/ArchUnitMojo has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
```

Please do let m know if there are any other option

**Comment by vincent-fuchs** [comment]
done : https://plugins.gradle.org/plugin/com.societegenerale.commons.arch-unit-gradle-plugin/3.1.0
